export const staffData = [
    {
        id: 1,
        image: '/images/staff/Alex-Esqueda.jpg',
        name: 'Alex Esqueda',
        yearStarted: 2013,
        accolades: [
            'Co-Owner, Head Coach ',
            'Program Designer CrossFit Decimate ',
            'Decimate Performance Training ',
            'CCFT/L-3 Certified CrossFit Trainer',
        ],
    },
    {
        id: 2,
        image: '/images/staff/Silvie-Esqueda.jpg',
        name: 'Silvie Esqueda',
        yearStarted: 2013,
        accolades: [
            'Co-Owner & Coach',
            'CF-L2',
            'USAW L-1',
            'Precision Nutrition L-1',
        ],
    },
    {
        id: 3,
        image: '/images/staff/Kara-Smith.jpg',
        name: 'Kara Smith',
        yearStarted: 2012,
        accolades: [
            'Lead Coach & Operations Assistant   ',
            '​CF-L2 Trainer',
            'ATA Certified: Adaptive & Inclusive Trainer',
            'The Phoenix (Volunteer)',
        ],
    },
    {
        id: 4,
        image: '/images/staff/Brook.jpg',
        name: 'Brook',
        yearStarted: 2019,
        accolades: [
            'Coach: Group Classes & Fundementals',
            'CF-L2 , Trainer',
            'ISSA Personal Trainer ',
            'Nutrition Coach',
        ],
    },
    {
        id: 5,
        image: '/images/staff/Amber-Dyett.jpg',
        name: 'Amber Dyett',
        yearStarted: 2016,
        accolades: [
            'Coach',
            'CF-L2',
            'PN-1',
            'BIRTHFIT Certified',
        ],
    },
    {
        id: 6,
        image: '/images/staff/Dr-Skyler-Harms.jpg',
        name: 'Dr Skyler Harms',
        yearStarted: 2010,
        accolades: [
            'Physical Therapist',
            'Doctor of Physical Therapy',
            'Titleist Performance Institute Certified',
            'Dry Needling Level 2',
        ],
    },
    {
        id: 7,
        image: '/images/staff/Elisa-Eastwood.jpg',
        name: 'Elisa Eastwood',
        yearStarted: 2014,
        accolades: [
            'Coach: Group Classes & Fundamentals',
            '​CF-L1',
            '2018 CF Regional Competitor',
        ],
    },
    {
        id: 8,
        image: '/images/staff/Jaque-Ong.jpg',
        name: 'Jaque Ong',
        yearStarted: 2012,
        accolades: [
            'Head Olympic Lifting Coach',
            'U.S.A.W',
            'IKKF Instructor',
            'Sports & Performance Cert Trainer',
        ],
    },
    {
        id: 9,
        image: '/images/staff/John-Giron.jpg',
        name: 'John Giron',
        yearStarted: 2010,
        accolades: [
            'Coach: Group Classes & Fundamentals',
            'CF-L1',
        ],
    },
    {
        id: 10,
        image: '/images/staff/Karlie-Goretski.jpg',
        name: 'Karlie Goretski',
        yearStarted: 2015,
        accolades: [
            'Coach: Kids CF',
            'CF-L1',
        ],
    },
    {
        id: 11,
        image: '/images/staff/Shana-Millspaugh.jpg',
        name: 'Shana Millspaugh',
        yearStarted: 2013,
        accolades: [
            'Coach',
            'CF-L1',
            'USAW L-1',
        ],
    },
];